No active exception to reraiseTraceback (most recent call last):
  File "C:\Users\z3531278\Documents\\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast_dev\python\initializeForecast.py", line 164, in <module>
    main()
  File "C:\Users\z3531278\Documents\\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast_dev\python\initializeForecast.py", line 109, in main
    raise
RuntimeError: No active exception to reraise
